### ISSUE TITLE
Add 'Star Wars: The Clone Wars' series

### ISSUE THREAD

**Issue by sleeyax** [TheBeastLT/stremio-tmdb-alternatives#1]
The usual recommended chronological order for this series is very different from cinemetas default order by release date. 

https://www.themoviedb.org/tv/4194-star-wars-the-clone-wars   

Chronological order: https://www.themoviedb.org/tv/4194-star-wars-the-clone-wars/episode_group/5b11ba820e0a265847002c6e/group/5b12ac77c3a36862a8006a85

**Comment by TheBeastLT** [comment]
Thanks for the suggestion! Is this only for watching order, as most scene torrents seem to be mapped correctly in the cinemetas ordering?

**Comment by sleeyax** [comment]
Yes, it's just the watching order.

**Comment by TheBeastLT** [comment]
My initial intention was to have this for series which have different mapping/ordering from torrent scene releases, but sure why not, we can include different watch order metas :)
